# Site settings
title: Chuik Blog
email: jinchuika@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  El blog donde (más tarde que temprano) comaprto todo lo que aprendo :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jinchuika.github.io/" # the base hostname & protocol for your site
twitter_username: chui_k
github_username:  jinchuika

# Build settings
markdown: kramdown
